# Generated by Django 3.2.16 on 2022-10-15 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40, verbose_name='Nickname')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('circuitos_digitais', 'Circuitos Digitais'), ('arquitetura_de_computadores', 'Arquitetura de Computadores'), ('sistemas_operacionais_1', 'Sistemas Operacionais 1'), ('sistemas_operacionais_2', 'Sistemas Operacionais 2')], max_length=99)),
                ('score', models.DecimalField(decimal_places=10, default=256, max_digits=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
    ]
