# Generated by Django 3.2.16 on 2022-11-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20221015_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='Easy', max_length=99, verbose_name='Dificuldade'),
        ),
        migrations.AlterField(
            model_name='round',
            name='score',
            field=models.DecimalField(decimal_places=0, default=256, max_digits=20),
        ),
    ]
