# Generated by Django 3.2.16 on 2022-11-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20221106_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='current_question',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
