# Generated by Django 3.2.16 on 2022-11-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_round_current_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nickname'),
        ),
    ]
