# Generated by Django 3.2.16 on 2022-11-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_player_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='answered_questions',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
