# Generated by Django 3.2.16 on 2022-11-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_round_answered_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='answered_questions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
