# Generated by Django 3.2.16 on 2022-11-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='PlayerAnswer',
        ),
    ]
