# Generated by Django 3.2.16 on 2022-11-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_rename_answer_playeranswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playeranswer',
            options={'verbose_name_plural': 'Players Answers'},
        ),
    ]
