# Generated by Django 3.2.16 on 2022-12-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_round_answered_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='current_question',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4),
        ),
    ]
