# Generated by Django 3.2.16 on 2022-12-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_question_question_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_number',
        ),
    ]
