# Generated by Django 3.2.16 on 2022-12-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_rename_question_number_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='score',
            field=models.DecimalField(decimal_places=0, default=64, max_digits=20),
        ),
    ]
