# Generated by Django 3.2.16 on 2022-12-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_round_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeranswer',
            name='is_final_answer',
            field=models.BooleanField(default=False, verbose_name='Final Answer'),
        ),
    ]
