# Generated by Django 3.2.16 on 2022-12-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_playeranswer_is_final_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeranswer',
            name='question_id',
        ),
        migrations.AddField(
            model_name='playeranswer',
            name='question_number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=99, verbose_name='Question Number'),
            preserve_default=False,
        ),
    ]
