# Generated by Django 3.2.16 on 2022-12-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20221214_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeranswer',
            name='is_final_answer',
            field=models.BooleanField(default=False, verbose_name='Is Final Answer'),
        ),
        migrations.AlterField(
            model_name='playeranswer',
            name='player_answer',
            field=models.CharField(max_length=99, verbose_name='Player Answer'),
        ),
    ]
