# Generated by Django 3.2.16 on 2023-01-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20221214_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('number', 'subject')},
        ),
    ]
